export type BibleBookType = {
  id: string;
  name: string;
  totalChapter: number;
};

export const BIBLE_BOOKS: BibleBookType[] = [
  { id: 'GEN', name: 'Genesis', totalChapter: 50 },
  { id: 'EXO', name: 'Exodus', totalChapter: 40 },
  { id: 'LEV', name: 'Leviticus', totalChapter: 27 },
  { id: 'NUM', name: 'Numbers', totalChapter: 36 },
  { id: 'DEU', name: 'Deuteronomy', totalChapter: 34 },
  { id: 'JOS', name: 'Joshua', totalChapter: 24 },
  { id: 'JDG', name: 'Judges', totalChapter: 21 },
  { id: 'RUT', name: 'Ruth', totalChapter: 4 },
  { id: '1SA', name: '1 Samuel', totalChapter: 31 },
  { id: '2SA', name: '2 Samuel', totalChapter: 24 },
  { id: '1KI', name: '1 Kings', totalChapter: 22 },
  { id: '2KI', name: '2 Kings', totalChapter: 25 },
  { id: '1CH', name: '1 Chronicles', totalChapter: 29 },
  { id: '2CH', name: '2 Chronicles', totalChapter: 36 },
  { id: 'EZR', name: 'Ezra', totalChapter: 10 },
  { id: 'NEH', name: 'Nehemiah', totalChapter: 13 },
  { id: 'EST', name: 'Esther', totalChapter: 10 },
  { id: 'JOB', name: 'Job', totalChapter: 42 },
  { id: 'PSA', name: 'Psalms', totalChapter: 150 },
  { id: 'PRO', name: 'Proverbs', totalChapter: 31 },
  { id: 'ECC', name: 'Ecclesiastes', totalChapter: 12 },
  { id: 'SNG', name: 'Song of Songs', totalChapter: 8 },
  { id: 'ISA', name: 'Isaiah', totalChapter: 66 },
  { id: 'JER', name: 'Jeremiah', totalChapter: 52 },
  { id: 'LAM', name: 'Lamentations', totalChapter: 5 },
  { id: 'EZK', name: 'Ezekiel', totalChapter: 48 },
  { id: 'DAN', name: 'Daniel', totalChapter: 12 },
  { id: 'HOS', name: 'Hosea', totalChapter: 14 },
  { id: 'JOL', name: 'Joel', totalChapter: 3 },
  { id: 'AMO', name: 'Amos', totalChapter: 9 },
  { id: 'OBA', name: 'Obadiah', totalChapter: 1 },
  { id: 'JON', name: 'Jonah', totalChapter: 4 },
  { id: 'MIC', name: 'Micah', totalChapter: 7 },
  { id: 'NAM', name: 'Nahum', totalChapter: 3 },
  { id: 'HAB', name: 'Habakkuk', totalChapter: 3 },
  { id: 'ZEP', name: 'Zephaniah', totalChapter: 3 },
  { id: 'HAG', name: 'Haggai', totalChapter: 2 },
  { id: 'ZEC', name: 'Zechariah', totalChapter: 14 },
  { id: 'MAL', name: 'Malachi', totalChapter: 4 },
  { id: 'MAT', name: 'Matthew', totalChapter: 28 },
  { id: 'MRK', name: 'Mark', totalChapter: 16 },
  { id: 'LUK', name: 'Luke', totalChapter: 24 },
  { id: 'JHN', name: 'John', totalChapter: 21 },
  { id: 'ACT', name: 'Acts', totalChapter: 28 },
  { id: 'ROM', name: 'Romans', totalChapter: 16 },
  { id: '1CO', name: '1 Corinthians', totalChapter: 16 },
  { id: '2CO', name: '2 Corinthians', totalChapter: 13 },
  { id: 'GAL', name: 'Galatians', totalChapter: 6 },
  { id: 'EPH', name: 'Ephesians', totalChapter: 6 },
  { id: 'PHP', name: 'Philippians', totalChapter: 4 },
  { id: 'COL', name: 'Colossians', totalChapter: 4 },
  { id: '1TH', name: '1 Thessalonians', totalChapter: 5 },
  { id: '2TH', name: '2 Thessalonians', totalChapter: 3 },
  { id: '1TI', name: '1 Timothy', totalChapter: 6 },
  { id: '2TI', name: '2 Timothy', totalChapter: 4 },
  { id: 'TIT', name: 'Titus', totalChapter: 3 },
  { id: 'PHM', name: 'Philemon', totalChapter: 1 },
  { id: 'HEB', name: 'Hebrews', totalChapter: 13 },
  { id: 'JAS', name: 'James', totalChapter: 5 },
  { id: '1PE', name: '1 Peter', totalChapter: 5 },
  { id: '2PE', name: '2 Peter', totalChapter: 3 },
  { id: '1JN', name: '1 John', totalChapter: 5 },
  { id: '2JN', name: '2 John', totalChapter: 1 },
  { id: '3JN', name: '3 John', totalChapter: 1 },
  { id: 'JUD', name: 'Jude', totalChapter: 1 },
  { id: 'REV', name: 'Revelation', totalChapter: 22 },
];

export const BIBLE_BOOK_MAP = BIBLE_BOOKS.reduce<{
  [bookId: string]: BibleBookType;
}>((acc, book) => {
  acc[book.id] = book;
  return acc;
}, {});
